/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./src/components/**/*.{js,ts,jsx,tsx}",
    "./src/sections/**/*.{js,jsx}",
    "./src/styles/**/*.{js,ts,jsx,tsx}",
    "./node_modules/tw-elements/dist/js/**/*.js",
  ],
  theme: {
    screens: {
      sm: "480px",
      md: "768px",
      lg: "976px",
      xl: "1440px",
    },
    extend: {
      colors: {
        primary: "#F15412",
        secondary: "#301003",
        danger: "#ff5252",
        success: "#198754",
        error: "#dc3545",
        info: "#0dcaf0",
        warning: "#FFC107",
        white: "#ffffff",
        lightPrimary: "#f4753e",
        veryLightPrimary: "#fbcbb7",
        // black: "#000000",
        // lightBlack: "#333333",
        // gray: "#9ca3af",
        // lightGray: "#f9fafb",
        // lightSecondary: "#f4753e",
        // veryLightGray: "#e5e7eb",
        // brightRed: "hsl(12, 88%, 59%)",
        // brightRedLight: "hsl(12, 88%, 69%)",
        // brightRedSupLight: "hsl(12, 88%, 95%)",
        // darkBlue: "hsl(228, 39%, 23%)",
        // darkGrayishBlue: "hsl(227, 12%, 61%)",
        // veryDarkBlue: "hsl(223, 12%, 13%)",
        // veryPaleRed: "hsl(13, 100%, 96%)",
      },
    },
  },
  plugins: [require("tw-elements/dist/plugin")],
};
